sudo: false

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

matrix:
  include:
    - php: 5.4
      env: WP_VERSION=4.4.2 PHP_LINT=1
    - php: 5.6
      env: WP_VERSION=latest PHP_LINT=1
    - php: 7.0
      env: WP_VERSION=latest PHP_LINT=1
    - php: 7.1
      env: WP_VERSION=latest PHP_LINT=1
    - php: 7.0
      env: WP_VERSION=nightly WP_PHPCS=1
    - php: 'hhvm'
      env: WP_VERSION=nightly PHP_LINT=1
  fast_finish: true

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then
      composer global require "phpunit/phpunit=5.7.*"
    else
      composer global require "phpunit/phpunit=4.8.*"
    fi

  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    fi
  - |
    if [[ "$WP_PHPCS" == "1" ]]; then
      composer install
      export PATH=$PATH:${PWD}/vendor/bin/
      # After CodeSniffer install you should refresh your path.
      phpenv rehash
    fi

  - phpunit --version

script:
  - if [[ "$PHP_LINT" == "1" ]]; then find . -type "f" -iname "*.php" | xargs -L "1" php -l; fi
  - if [[ "$WP_PHPCS" == "1" ]]; then phpcs -p -s -v -n --standard=./codesniffer.ruleset.xml --extensions=php .; fi
  - phpunit
  - phpunit -c multisite.xml
